<?php include "includes/header.php"?>
    <p>The topic of responsive websites versus native mobile applications is especially pertinent today: “With more than 3.5 billion smartphone users in the world today, it’s no longer a question of whether you should adapt products for mobile devices, but rather how to do it properly” (Babich). Developers must decide between a native mobile app or a responsive web platform, or both, and there are a few major differences between these options that must be weighed. As the Clearbridge site stated, “Deciding which medium serves your needs best depends on several factors, including target audiences, budget, and intent.” </p>
<p>Responsive web design is intended for mobile and desktop use. “Responsive web design uses fluid grid systems (flexible grids that use relative sizes rather than absolute ones), fluid images (images that scale to fit the grids), and media queries (to alter the layout of the site when certain conditions are met)” (Babich). A mobile responsive site would feature a different url and subsets of the desktop content reformatted for mobile viewing. A mobile application is specifically formatted to each operating system, with specific designs and code. </p>
<p>There are many pros and cons to each option. First, responsive web design: designing a responsive site is quicker than designing an application, and therefore can also be more cost effective. A responsive site is available to all users, regardless of whether they are accessing on a phone or a desktop. Users don’t have to download or update an app, and websites are easier to share. Responsive sites are more adaptive to screen sizes and have better cross platform accessibility. </p>
<p>The cons of responsive sites are equally important. “As they say, you get what you pay for. Responsive mobile sites, while necessary in today’s business climate, aren’t as fast or as functional as native mobile apps. It takes a long time to navigate to a mobile site through a phone’s browser when compared with the convenience of an app, and once users are there, the platform usually performs slower” (Kris). Responsive mobile sites require the internet, cannot be distributed through an app store, and offer limited support of native device features. </p>
<p>Native applications have innumerable pros, such as greater functionality. The application is custom built into the OS; “this means that apps can easily integrate with other features and tools in a device as well as support functions that aren’t possible with web-based HTML5” (Kris). Apps are designed with efficiency in mind, they are faster and more responsive. The UX is most important, so they are less cluttered and the experience is streamlined, as well as being customizable to each user. Apps can offer different channels of engagement and help with brand recognition. Also, apps can work without an internet connection. The cons of apps are that the cost and time to create them can be prohibitive to smaller businesses. They are also based on a specific OS, so can’t run on devices outside of that. </p>
<p>Both responsive sites and native applications are very useful. “Statistically speaking, the numbers do favor mobile apps. A recent report from Sensor Tower revealed that consumer spending on mobile apps and app installs grew significantly during the first half of 2020, reaching $50.1 billion worldwide across the App Store and Google Play (Clearbidge).” Most companies will need to get both a mobile responsive website as well as an app, if they can. As Babich wrote, “Carefully specify your business goals and find the right way (or ways) to achieve these goals using a responsive web app, native apps, or a combination of both.”
</p>
    
</section>
<!-- END LEFT COL -->

<!-- START RIGHT COL -->
<aside class="citation box">
 <h3>Citations</h3>
 <p>Babich, Nick. “Deciding Between Responsive Web or Native Apps: Adobe XD Ideas.”	 Adobe XD Ideas, 7 Apr. 2020, <a href="https://xd.adobe.com/ideas/principles/web-design/responsive-web-or-native-app/" target="_blank">xd.adobe.com</a></p>
<p>“Mobile App Vs. Mobile Website: Which Is The Better Option?” Clearbridge Mobile, 11 July 2020, <a href="https://clearbridgemobile.com/mobile-app-vs-mobile-website-which-is-the-better-option/" target="_blank">clearbridgemobile.com</a>  </p>
    <p>Kris. “The Pros and Cons of Mobile Apps vs. Responsive Web Design.” Smashstack, 5 Jan. 2017, <a href="https://www.smashstack.com/articles/the-pros-and-cons-of-mobile-apps-vs-responsive-web-design/" target="_blank">smashstack.com</a> </p>
</aside>
<!-- END RIGHT COL -->
 <?php include "includes/footer.php"?>